version: "3"

services:
    api:
        build: .
        depends_on:
            - mongo
        environment:
            - PORT=5000
            - MONGO_URI=mongodb://mongo:27017/test
            - APP_NAME=Share your idea
            - JWT_SECRET=JFHUGYRTEUDHF75647564
            - CACHE_KEY=myStrongPassword
            - SWAGGER_DOC=swaggerPROD
        ports: 
            - "5000:5000"

    mongo:
        image: mongo